const fs=require('fs');
const path=require('path');
const sharp=require('/home/parsa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=__dirname;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
(async()=>{
 const entries=[];
 for(const dir of fs.readdirSync(root).filter(n=>/^\d\d-/.test(n)).sort()){
  const logo=path.join(root,dir,'logo.svg'), meta=path.join(root,dir,'concept.json');
  if(!fs.existsSync(logo)||!fs.existsSync(meta)) continue;
  const data=JSON.parse(fs.readFileSync(meta));
  await sharp(logo).png().toFile(path.join(root,dir,'logo.png'));
  if(fs.existsSync(path.join(root,dir,'mark.svg'))) await sharp(path.join(root,dir,'mark.svg')).png().toFile(path.join(root,dir,'mark.png'));
  entries.push({...data,id:parseInt(dir),dir,set:parseInt(dir)<=10?'A':'B'});
 }
 fs.writeFileSync(path.join(root,'manifest.json'),JSON.stringify(entries,null,2));
 const cards=entries.map(e=>`<article data-set="${e.set}" id="concept-${e.id}"><button class="art" aria-label="Enlarge ${escape(e.name)}" data-img="${e.dir}/logo.png"><img src="${e.dir}/logo.svg" alt="${escape(e.name)} — Push-Up Bird logo concept"></button><div class="caption"><span class="number">${String(e.id).padStart(2,'0')}</span><div><h2>${escape(e.name)}</h2><p>${escape(e.rationale)}</p><nav><a href="${e.dir}/logo.svg" download>SVG</a><a href="${e.dir}/logo.png" download>PNG</a>${fs.existsSync(path.join(root,e.dir,'mark.svg'))?`<a href="${e.dir}/mark.svg" download>Icon</a>`:''}</nav></div></div></article>`).join('\n');
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Push-Up Bird · 20 Logo Concepts</title><style>
 @font-face{font-family:Fredoka;src:url('fonts/Fredoka.ttf')}@font-face{font-family:Nunito;src:url('fonts/Nunito.ttf')}
 *{box-sizing:border-box}body{margin:0;background:#f2f0e9;color:#203b45;font-family:Nunito,system-ui,sans-serif}header{padding:64px 5vw 32px;max-width:1800px;margin:auto}.eyebrow{font-size:12px;letter-spacing:2px;text-transform:uppercase;font-weight:900}h1{font:600 clamp(40px,5vw,74px)/1.05 Fredoka,sans-serif;letter-spacing:-2px;margin:18px 0}header p{max-width:690px;font-size:17px;line-height:1.6;margin:0 0 24px}a{color:inherit}header>a{font-weight:800} .filters{display:flex;gap:10px;margin-top:28px;flex-wrap:wrap}.filters button{border:1px solid #b6bfb9;background:transparent;border-radius:30px;padding:10px 18px;color:inherit;font:800 13px Nunito;cursor:pointer}.filters button[aria-pressed=true]{background:#203b45;color:#fff9ed;border-color:#203b45}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:32px 22px;padding:20px 5vw 70px;max-width:1800px;margin:auto}article{min-width:0;scroll-margin:24px}.art{width:100%;display:block;padding:0;border:1px solid #203b4512;border-radius:15px;overflow:hidden;cursor:zoom-in;background:#fff9ed;aspect-ratio:4/3}.art img{width:100%;height:100%;object-fit:contain;display:block;transition:transform .25s}.art:hover img{transform:scale(1.03)}.caption{display:flex;gap:12px;margin-top:16px}.number{font-size:13px;opacity:.55;padding-top:3px;font-weight:900}h2{font:600 21px Fredoka;margin:0 0 8px}.caption p{font-size:13px;line-height:1.5;margin:0;opacity:.78}nav{display:flex;gap:15px;margin-top:12px;font-weight:900;font-size:12px}dialog{border:0;border-radius:18px;padding:0;background:#fff9ed;max-width:min(1200px,94vw);max-height:94vh}dialog::backdrop{background:#10282dcc;backdrop-filter:blur(8px)}dialog img{display:block;max-width:100%;max-height:88vh}dialog button{position:absolute;right:12px;top:12px;border:0;background:#203b45;color:white;width:34px;height:34px;border-radius:50%;font-size:22px;cursor:pointer}footer{border-top:1px solid #203b4522;padding:24px 5vw 40px;font-size:13px;line-height:1.7}body:has(dialog[open]){overflow:hidden}[hidden]{display:none!important}@media(max-width:1200px){.grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:800px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}header{padding-top:38px}}@media(max-width:520px){.grid{grid-template-columns:1fr}h1{letter-spacing:-1px}}@media(prefers-reduced-motion:reduce){.art img{transition:none}}
 </style></head><body><header><div class="eyebrow">Push-Up Bird / Identity exploration / 03 October 2026</div><h1>One game.<br>Twenty ways to take flight.</h1><p>Twenty independent agents explored the birds, stars, islands and motion of Push-Up Bird. Select any logo to inspect it, or download its editable vector artwork.</p><a href="https://www.figma.com/design/V5T8hRN8kuh2OQ8oISugR8" target="_blank" rel="noopener">Open the Figma board ↗</a><div class="filters"><button data-filter="all" aria-pressed="true">All 20 concepts</button><button data-filter="A" aria-pressed="false">01–10 · Current model</button><button data-filter="B" aria-pressed="false">11–20 · GPT‑6.1 Sol</button></div></header><main class="grid">${cards}</main><footer>All twenty designs are concepts. SVG files contain editable vector geometry with outlined type.<br>Game-inspired vector artwork · Fredoka / Nunito, with Z003 script in concept 12. <a href="contact-sheet.png">Download comparison sheet</a> · <a href="logo-concepts.zip">Download all concepts</a></footer><dialog aria-label="Logo preview"><button aria-label="Close preview">×</button><img alt="Enlarged logo concept"></dialog><script>
 const modal=document.querySelector('dialog');document.querySelectorAll('.art').forEach(b=>b.onclick=()=>{modal.querySelector('img').src=b.dataset.img;modal.querySelector('img').alt=b.getAttribute('aria-label').replace('Enlarge','Logo concept:');modal.showModal()});modal.querySelector('button').onclick=()=>modal.close();modal.onclick=e=>{if(e.target===modal)modal.close()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelectorAll('article').forEach(a=>a.hidden=b.dataset.filter!=='all'&&a.dataset.set!==b.dataset.filter)});
 </script></body></html>`;
 fs.writeFileSync(path.join(root,'index.html'),html);
 console.log(JSON.stringify({rendered:entries.length,concepts:entries.map(e=>`${e.id}: ${e.name}`)},null,2));
})();
