// Generated by tool/l10n/prepare_localized_voices.py --wire. Do not edit.
// The fr voice pack: an asset-only Flutter deferred component
// (pubspec.yaml, deferred-components) that Google Play delivers on demand.
plugins {
    id("com.android.dynamic-feature")
}

android {
    namespace = "com.ravanix.push_up_bird.voice_fr"
    compileSdk = 36

    defaultConfig {
        minSdk = 24
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildTypes {
        create("profile") {
            initWith(getByName("debug"))
        }
    }

    // `flutter build appbundle` copies the pack's assets here; every other
    // build keeps them in the base module.
    sourceSets {
        for (mode in listOf("debug", "profile", "release")) {
            // A File: AGP refuses a Provider in the source set API.
            getByName(mode).assets.srcDir(
                layout.buildDirectory.dir("intermediates/flutter/$mode/deferred_assets")
                    .get().asFile
            )
        }
    }
}

dependencies {
    implementation(project(":app"))
}

// The assets are written by :app's Flutter build task; Gradle 9 refuses to
// read another task's output without the dependency said.
tasks.configureEach {
    val mode = Regex("merge(Debug|Profile|Release)Assets").matchEntire(name)?.groupValues?.get(1)
    if (mode != null) dependsOn(":app:compileFlutterBuild$mode")
}
