// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum TrackingApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum DetectorKind: Int, CaseIterable {
  case pose = 0
  case face = 1
}

enum CameraAccess: Int, CaseIterable {
  case granted = 0
  case denied = 1
  case permanentlyDenied = 2
  case unavailable = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct LandmarkPacket: Hashable, CustomStringConvertible {
  var x: Double
  var y: Double
  var z: Double
  var confidence: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LandmarkPacket? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let z = pigeonVar_list[2] as! Double
    let confidence = pigeonVar_list[3] as! Double

    return LandmarkPacket(
      x: x,
      y: y,
      z: z,
      confidence: confidence
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      z,
      confidence,
    ]
  }
  static func == (lhs: LandmarkPacket, rhs: LandmarkPacket) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return TrackingApiPigeonInternal.deepEquals(lhs.x, rhs.x) && TrackingApiPigeonInternal.deepEquals(lhs.y, rhs.y) && TrackingApiPigeonInternal.deepEquals(lhs.z, rhs.z) && TrackingApiPigeonInternal.deepEquals(lhs.confidence, rhs.confidence)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LandmarkPacket")
    TrackingApiPigeonInternal.deepHash(value: x, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: y, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: z, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: confidence, hasher: &hasher)
  }

  public var description: String {
    return "LandmarkPacket(x: \(String(describing: x)), y: \(String(describing: y)), z: \(String(describing: z)), confidence: \(String(describing: confidence)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TrackingPacket: Hashable, CustomStringConvertible {
  var session: Int64
  var detector: DetectorKind
  var capturedAtMs: Int64
  var sentAtMs: Int64
  var inferenceMs: Double
  var imageWidth: Int64
  var imageHeight: Int64
  var landmarks: [LandmarkPacket]
  var smile: Double
  var detected: Bool
  var sensorTimestamp: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TrackingPacket? {
    let session = pigeonVar_list[0] as! Int64
    let detector = pigeonVar_list[1] as! DetectorKind
    let capturedAtMs = pigeonVar_list[2] as! Int64
    let sentAtMs = pigeonVar_list[3] as! Int64
    let inferenceMs = pigeonVar_list[4] as! Double
    let imageWidth = pigeonVar_list[5] as! Int64
    let imageHeight = pigeonVar_list[6] as! Int64
    let landmarks = pigeonVar_list[7] as! [LandmarkPacket]
    let smile = pigeonVar_list[8] as! Double
    let detected = pigeonVar_list[9] as! Bool
    let sensorTimestamp = pigeonVar_list[10] as! Bool

    return TrackingPacket(
      session: session,
      detector: detector,
      capturedAtMs: capturedAtMs,
      sentAtMs: sentAtMs,
      inferenceMs: inferenceMs,
      imageWidth: imageWidth,
      imageHeight: imageHeight,
      landmarks: landmarks,
      smile: smile,
      detected: detected,
      sensorTimestamp: sensorTimestamp
    )
  }
  func toList() -> [Any?] {
    return [
      session,
      detector,
      capturedAtMs,
      sentAtMs,
      inferenceMs,
      imageWidth,
      imageHeight,
      landmarks,
      smile,
      detected,
      sensorTimestamp,
    ]
  }
  static func == (lhs: TrackingPacket, rhs: TrackingPacket) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return TrackingApiPigeonInternal.deepEquals(lhs.session, rhs.session) && TrackingApiPigeonInternal.deepEquals(lhs.detector, rhs.detector) && TrackingApiPigeonInternal.deepEquals(lhs.capturedAtMs, rhs.capturedAtMs) && TrackingApiPigeonInternal.deepEquals(lhs.sentAtMs, rhs.sentAtMs) && TrackingApiPigeonInternal.deepEquals(lhs.inferenceMs, rhs.inferenceMs) && TrackingApiPigeonInternal.deepEquals(lhs.imageWidth, rhs.imageWidth) && TrackingApiPigeonInternal.deepEquals(lhs.imageHeight, rhs.imageHeight) && TrackingApiPigeonInternal.deepEquals(lhs.landmarks, rhs.landmarks) && TrackingApiPigeonInternal.deepEquals(lhs.smile, rhs.smile) && TrackingApiPigeonInternal.deepEquals(lhs.detected, rhs.detected) && TrackingApiPigeonInternal.deepEquals(lhs.sensorTimestamp, rhs.sensorTimestamp)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TrackingPacket")
    TrackingApiPigeonInternal.deepHash(value: session, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: detector, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: capturedAtMs, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: sentAtMs, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: inferenceMs, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: imageWidth, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: imageHeight, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: landmarks, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: smile, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: detected, hasher: &hasher)
    TrackingApiPigeonInternal.deepHash(value: sensorTimestamp, hasher: &hasher)
  }

  public var description: String {
    return "TrackingPacket(session: \(String(describing: session)), detector: \(String(describing: detector)), capturedAtMs: \(String(describing: capturedAtMs)), sentAtMs: \(String(describing: sentAtMs)), inferenceMs: \(String(describing: inferenceMs)), imageWidth: \(String(describing: imageWidth)), imageHeight: \(String(describing: imageHeight)), landmarks: \(String(describing: landmarks)), smile: \(String(describing: smile)), detected: \(String(describing: detected)), sensorTimestamp: \(String(describing: sensorTimestamp)))"
  }
}

private class TrackingApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DetectorKind(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraAccess(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return LandmarkPacket.fromList(self.readValue() as! [Any?])
    case 132:
      return TrackingPacket.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class TrackingApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DetectorKind {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraAccess {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? LandmarkPacket {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? TrackingPacket {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class TrackingApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TrackingApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TrackingApiPigeonCodecWriter(data: data)
  }
}

class TrackingApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = TrackingApiPigeonCodec(readerWriter: TrackingApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TrackingHostApi {
  func requestCamera(completion: @escaping (Result<CameraAccess, Error>) -> Void)
  func start(detector: DetectorKind, frontCamera: Bool, session: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func stop(completion: @escaping (Result<Void, Error>) -> Void)
  func monotonicTimeMs() throws -> Int64
  func openAppSettings() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TrackingHostApiSetup {
  static var codec: FlutterStandardMessageCodec { TrackingApiPigeonCodec.shared }
  /// Sets up an instance of `TrackingHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TrackingHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let requestCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.push_up_bird.TrackingHostApi.requestCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestCameraChannel.setMessageHandler { _, reply in
        api.requestCamera { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestCameraChannel.setMessageHandler(nil)
    }
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.push_up_bird.TrackingHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let detectorArg = args[0] as! DetectorKind
        let frontCameraArg = args[1] as! Bool
        let sessionArg = args[2] as! Int64
        api.start(detector: detectorArg, frontCamera: frontCameraArg, session: sessionArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.push_up_bird.TrackingHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        api.stop { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let monotonicTimeMsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.push_up_bird.TrackingHostApi.monotonicTimeMs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      monotonicTimeMsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.monotonicTimeMs()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      monotonicTimeMsChannel.setMessageHandler(nil)
    }
    let openAppSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.push_up_bird.TrackingHostApi.openAppSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openAppSettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openAppSettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openAppSettingsChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol TrackingFlutterApiProtocol {
  func onSample(packet packetArg: TrackingPacket) async throws
  func onStatus(session sessionArg: Int64, code codeArg: String, message messageArg: String) async throws
}
class TrackingFlutterApi: TrackingFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: TrackingApiPigeonCodec {
    return TrackingApiPigeonCodec.shared
  }
  func onSample(packet packetArg: TrackingPacket) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.push_up_bird.TrackingFlutterApi.onSample\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([packetArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onStatus(session sessionArg: Int64, code codeArg: String, message messageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.push_up_bird.TrackingFlutterApi.onStatus\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([sessionArg, codeArg, messageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
