#!/usr/bin/env python3
"""Writes the pseudo-locale lib/l10n/arb/app_en_XA.arb from the template.

  python3 tool/l10n/pseudo_arb.py

Every message's literal text is accented with letters both Fredoka and
Nunito draw, every other vowel is doubled, and the message is wrapped in
`[` `]` and padded with `~` to about 140 % of the English length, the same
rules as pseudoLocalize() in lib/l10n/pseudo.dart. Placeholders, plural
and select keywords are left alone. merge_arb.py runs this; run it by hand
after editing app_en.arb directly. Then `flutter gen-l10n`.
"""
from __future__ import annotations

import math
import os
import re
import sys
from collections import OrderedDict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import arb_lib as L  # noqa: E402

ACCENTS = {
    'a': 'á', 'c': 'ç', 'd': 'ð', 'e': 'é', 'f': 'ƒ', 'i': 'í', 'l': 'ł',
    'n': 'ñ', 'o': 'ö', 'p': 'þ', 's': 'š', 'u': 'ü', 'y': 'ý', 'z': 'ž',
    'A': 'Å', 'C': 'Ç', 'D': 'Ð', 'E': 'É', 'I': 'Î', 'L': 'Ł', 'N': 'Ñ',
    'O': 'Ø', 'P': 'Þ', 'S': 'Š', 'U': 'Û', 'Y': 'Ý', 'Z': 'Ž',
}


def pseudo_message(text: str) -> str:
    nodes = L.parse(text)
    state = {'vowels': 0, 'added': 0}

    def run(t: str) -> str:
        out = []
        for ch in t:
            a = ACCENTS.get(ch, ch)
            out.append(a)
            if ch in 'aeiouAEIOU':
                if state['vowels'] % 2 == 0:
                    out.append(a)
                    state['added'] += 1
                state['vowels'] += 1
        return ''.join(out)

    body = L.rebuild(nodes, run)
    # Letters of the longest way the message reads.
    letters = max(len(re.findall('[A-Za-z]', v)) for v in L.variants(nodes))
    pad = max(0, math.ceil(letters * .4) - state['added'] // max(1, len(L.variants(nodes))))
    return f'[{body}{"~" * pad}]'


def write():
    template = L.load_json(L.TEMPLATE)
    out = OrderedDict([
        ('@@locale', L.PSEUDO),
        ('@@x-note', 'Generated by tool/l10n/pseudo_arb.py. Do not edit or translate.'),
    ])
    for key, text in L.messages(template).items():
        meta = template.get('@' + key) or {}
        # A switch's value ("x-choices") is read by code, not shown.
        out[key] = text if meta.get('x-choices') else pseudo_message(text)
    L.dump_json(out, L.arb_path(L.PSEUDO))
    return len(out) - 2


if __name__ == '__main__':
    print(f'app_{L.PSEUDO}.arb: {write()} messages')
