#!/usr/bin/env python3
"""Master the campaign story's voice-over. Requires FFmpeg; no network.

The takes were generated with ElevenLabs Eleven v4. Each clip's voice,
prompt and generation id are listed in docs/story-voices-sources.json. The
downloaded takes belong in build/story-voices/source/<name>.mp3 (ignored).

Every take is trimmed to its speech with a short breath of room either side,
brought to one loudness so no character shouts over another, and saved as a
mono Ogg Vorbis file in assets/audio/story/. The clip lengths are written to
lib/game/campaign_voice_clips.dart, which the game reads to pace each line.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / 'docs' / 'story-voices-sources.json'
SOURCE_DIR = ROOT / 'build' / 'story-voices' / 'source'
OUT_DIR = ROOT / 'assets' / 'audio' / 'story'
CLIPS_DART = ROOT / 'lib' / 'game' / 'campaign_voice_clips.dart'
VERIFY = ROOT / 'build' / 'story-voices' / 'verification.json'

# Speech sits under the music at the level of the existing voice cues.
LOUDNESS = -18.0
TRUE_PEAK = -1.5
# Room kept before the first word and after the last, in seconds.
LEAD, TAIL = .04, .12
SILENCE_DB = -48


def measure(path):
    """The take's loudness, as loudnorm's first pass measures it."""
    out = subprocess.run(
        ['ffmpeg', '-hide_banner', '-nostats', '-i', str(path), '-af',
         f'loudnorm=I={LOUDNESS}:TP={TRUE_PEAK}:LRA=11:print_format=json',
         '-f', 'null', '-'],
        capture_output=True, text=True, check=True,
    ).stderr
    return json.loads(out[out.rindex('{'):out.rindex('}') + 1])


def probe(path):
    return float(subprocess.check_output(
        ['ffprobe', '-v', 'error', '-show_entries', 'format=duration',
         '-of', 'default=nw=1:nk=1', str(path)], text=True))


def speech_bounds(path):
    """Where the speech starts and ends, from FFmpeg's silence detector."""
    out = subprocess.run(
        ['ffmpeg', '-hide_banner', '-nostats', '-i', str(path), '-af',
         f'silencedetect=n={SILENCE_DB}dB:d=0.08', '-f', 'null', '-'],
        capture_output=True, text=True, check=True,
    ).stderr
    duration = probe(path)
    starts = [float(v) for v in re.findall(r'silence_start: ([\d.]+)', out)]
    ends = [float(v) for v in re.findall(r'silence_end: ([\d.]+)', out)]
    begin, finish = 0.0, duration
    # Silence that opens the take ends where the speech begins.
    if starts and starts[0] <= .01 and ends:
        begin = ends[0]
    # Silence that runs to the end of the take starts where the speech ends.
    if starts and (len(ends) < len(starts) or ends[-1] >= duration - .01):
        finish = starts[-1]
    return max(0.0, begin - LEAD), min(duration, finish + TAIL)


def master(source, target, rate=44100):
    start, end = speech_bounds(source)
    m = measure(source)
    loudnorm = (
        f'loudnorm=I={LOUDNESS}:TP={TRUE_PEAK}:LRA=11'
        f":measured_I={m['input_i']}:measured_TP={m['input_tp']}"
        f":measured_LRA={m['input_lra']}:measured_thresh={m['input_thresh']}"
        f":offset={m['target_offset']}:linear=true"
    )
    fades = f'afade=t=in:d=0.02,afade=t=out:st={max(0, end - start - .05):.3f}:d=0.05'
    subprocess.run(
        ['ffmpeg', '-hide_banner', '-v', 'error', '-y', '-i', str(source),
         '-ss', f'{start:.3f}', '-to', f'{end:.3f}',
         '-af', f'{loudnorm},{fades},aresample={rate}',
         '-ac', '1', '-c:a', 'libvorbis', '-q:a', '2', str(target)],
        check=True,
    )
    duration = probe(target)
    return duration


def write_clips(lengths):
    lines = [
        '// Generated by tool/prepare_story_voices.py. Do not edit.',
        '',
        '/// Every recorded story clip in assets/audio/story/, by name, with',
        '/// how long it plays in milliseconds.',
        'const campaignVoiceClips = <String, int>{',
    ]
    lines += [f"  '{name}': {ms}," for name, ms in sorted(lengths.items())]
    lines += ['};', '']
    CLIPS_DART.write_text('\n'.join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--only', nargs='*', help='clip names to redo')
    args = parser.parse_args()
    clips = json.loads(SOURCES.read_text())['clips']
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    old = {}
    if CLIPS_DART.exists():
        old = {m[0]: int(m[1]) for m in re.findall(
            r"'([\w-]+)': (\d+),", CLIPS_DART.read_text())}
    lengths, report = {}, {}
    for clip in clips:
        name = clip['name']
        target = OUT_DIR / f'{name}.ogg'
        if args.only and name not in args.only and name in old:
            lengths[name] = old[name]
            continue
        source = SOURCE_DIR / f'{name}.mp3'
        if not source.exists():
            raise SystemExit(f'Missing source take: {source}')
        seconds = master(source, target)
        lengths[name] = round(seconds * 1000)
        report[name] = {
            'seconds': round(seconds, 3),
            'bytes': target.stat().st_size,
            'sha256': hashlib.sha256(target.read_bytes()).hexdigest(),
        }
    write_clips(lengths)
    VERIFY.parent.mkdir(parents=True, exist_ok=True)
    VERIFY.write_text(json.dumps(report, indent=1))
    total = sum(p.stat().st_size for p in OUT_DIR.glob('*.ogg'))
    print(f'{len(lengths)} clips, {sum(lengths.values()) / 1000:.1f} s, '
          f'{total / 1e6:.2f} MB')


if __name__ == '__main__':
    main()
