// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.ravanix.push_up_bird

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object TrackingApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class DetectorKind(val raw: Int) {
  POSE(0),
  FACE(1);

  companion object {
    fun ofRaw(raw: Int): DetectorKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CameraAccess(val raw: Int) {
  GRANTED(0),
  DENIED(1),
  PERMANENTLY_DENIED(2),
  UNAVAILABLE(3);

  companion object {
    fun ofRaw(raw: Int): CameraAccess? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MicrophoneAccess(val raw: Int) {
  GRANTED(0),
  DENIED(1),
  PERMANENTLY_DENIED(2),
  UNAVAILABLE(3);

  companion object {
    fun ofRaw(raw: Int): MicrophoneAccess? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LandmarkPacket (
  val x: Double,
  val y: Double,
  val z: Double,
  val confidence: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LandmarkPacket {
      val x = pigeonVar_list[0] as Double
      val y = pigeonVar_list[1] as Double
      val z = pigeonVar_list[2] as Double
      val confidence = pigeonVar_list[3] as Double
      return LandmarkPacket(x, y, z, confidence)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
      z,
      confidence,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LandmarkPacket
    return TrackingApiPigeonUtils.deepEquals(this.x, other.x) && TrackingApiPigeonUtils.deepEquals(this.y, other.y) && TrackingApiPigeonUtils.deepEquals(this.z, other.z) && TrackingApiPigeonUtils.deepEquals(this.confidence, other.confidence)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.x)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.y)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.z)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.confidence)
    return result
  }
  override fun toString(): String {
    return "LandmarkPacket(x=$x, y=$y, z=$z, confidence=$confidence)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TrackingPacket (
  val session: Long,
  val detector: DetectorKind,
  val capturedAtMs: Long,
  val sentAtMs: Long,
  val inferenceMs: Double,
  val imageWidth: Long,
  val imageHeight: Long,
  val landmarks: List<LandmarkPacket>,
  val smile: Double,
  val detected: Boolean,
  val sensorTimestamp: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrackingPacket {
      val session = pigeonVar_list[0] as Long
      val detector = pigeonVar_list[1] as DetectorKind
      val capturedAtMs = pigeonVar_list[2] as Long
      val sentAtMs = pigeonVar_list[3] as Long
      val inferenceMs = pigeonVar_list[4] as Double
      val imageWidth = pigeonVar_list[5] as Long
      val imageHeight = pigeonVar_list[6] as Long
      val landmarks = pigeonVar_list[7] as List<LandmarkPacket>
      val smile = pigeonVar_list[8] as Double
      val detected = pigeonVar_list[9] as Boolean
      val sensorTimestamp = pigeonVar_list[10] as Boolean
      return TrackingPacket(session, detector, capturedAtMs, sentAtMs, inferenceMs, imageWidth, imageHeight, landmarks, smile, detected, sensorTimestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      session,
      detector,
      capturedAtMs,
      sentAtMs,
      inferenceMs,
      imageWidth,
      imageHeight,
      landmarks,
      smile,
      detected,
      sensorTimestamp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TrackingPacket
    return TrackingApiPigeonUtils.deepEquals(this.session, other.session) && TrackingApiPigeonUtils.deepEquals(this.detector, other.detector) && TrackingApiPigeonUtils.deepEquals(this.capturedAtMs, other.capturedAtMs) && TrackingApiPigeonUtils.deepEquals(this.sentAtMs, other.sentAtMs) && TrackingApiPigeonUtils.deepEquals(this.inferenceMs, other.inferenceMs) && TrackingApiPigeonUtils.deepEquals(this.imageWidth, other.imageWidth) && TrackingApiPigeonUtils.deepEquals(this.imageHeight, other.imageHeight) && TrackingApiPigeonUtils.deepEquals(this.landmarks, other.landmarks) && TrackingApiPigeonUtils.deepEquals(this.smile, other.smile) && TrackingApiPigeonUtils.deepEquals(this.detected, other.detected) && TrackingApiPigeonUtils.deepEquals(this.sensorTimestamp, other.sensorTimestamp)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.session)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.detector)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.capturedAtMs)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.sentAtMs)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.inferenceMs)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.imageWidth)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.imageHeight)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.landmarks)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.smile)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.detected)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.sensorTimestamp)
    return result
  }
  override fun toString(): String {
    return "TrackingPacket(session=$session, detector=$detector, capturedAtMs=$capturedAtMs, sentAtMs=$sentAtMs, inferenceMs=$inferenceMs, imageWidth=$imageWidth, imageHeight=$imageHeight, landmarks=$landmarks, smile=$smile, detected=$detected, sensorTimestamp=$sensorTimestamp)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CameraClip (
  val path: String,
  val startedAtMs: Long,
  val durationMs: Long,
  val hasAudio: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraClip {
      val path = pigeonVar_list[0] as String
      val startedAtMs = pigeonVar_list[1] as Long
      val durationMs = pigeonVar_list[2] as Long
      val hasAudio = pigeonVar_list[3] as Boolean
      return CameraClip(path, startedAtMs, durationMs, hasAudio)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      startedAtMs,
      durationMs,
      hasAudio,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CameraClip
    return TrackingApiPigeonUtils.deepEquals(this.path, other.path) && TrackingApiPigeonUtils.deepEquals(this.startedAtMs, other.startedAtMs) && TrackingApiPigeonUtils.deepEquals(this.durationMs, other.durationMs) && TrackingApiPigeonUtils.deepEquals(this.hasAudio, other.hasAudio)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.path)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.startedAtMs)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + TrackingApiPigeonUtils.deepHash(this.hasAudio)
    return result
  }
  override fun toString(): String {
    return "CameraClip(path=$path, startedAtMs=$startedAtMs, durationMs=$durationMs, hasAudio=$hasAudio)"
  }
}
private open class TrackingApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DetectorKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraAccess.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MicrophoneAccess.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LandmarkPacket.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrackingPacket.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraClip.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DetectorKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is CameraAccess -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is MicrophoneAccess -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is LandmarkPacket -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is TrackingPacket -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is CameraClip -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TrackingHostApi {
  fun requestCamera(callback: (Result<CameraAccess>) -> Unit)
  fun microphoneAccess(): MicrophoneAccess
  fun requestMicrophone(callback: (Result<MicrophoneAccess>) -> Unit)
  fun start(detector: DetectorKind, frontCamera: Boolean, session: Long, callback: (Result<Unit>) -> Unit)
  fun stop(callback: (Result<Unit>) -> Unit)
  fun startRecording(withAudio: Boolean, callback: (Result<Long>) -> Unit)
  fun stopRecording(callback: (Result<CameraClip?>) -> Unit)
  fun monotonicTimeMs(): Long
  fun openAppSettings()

  companion object {
    /** The codec used by TrackingHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      TrackingApiPigeonCodec()
    }
    /** Sets up an instance of `TrackingHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TrackingHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.push_up_bird.TrackingHostApi.requestCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestCamera{ result: Result<CameraAccess> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TrackingApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TrackingApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.push_up_bird.TrackingHostApi.microphoneAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.microphoneAccess())
            } catch (exception: Throwable) {
              TrackingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.push_up_bird.TrackingHostApi.requestMicrophone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestMicrophone{ result: Result<MicrophoneAccess> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TrackingApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TrackingApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.push_up_bird.TrackingHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val detectorArg = args[0] as DetectorKind
            val frontCameraArg = args[1] as Boolean
            val sessionArg = args[2] as Long
            api.start(detectorArg, frontCameraArg, sessionArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TrackingApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(TrackingApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.push_up_bird.TrackingHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stop{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TrackingApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(TrackingApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.push_up_bird.TrackingHostApi.startRecording$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val withAudioArg = args[0] as Boolean
            api.startRecording(withAudioArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TrackingApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TrackingApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.push_up_bird.TrackingHostApi.stopRecording$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopRecording{ result: Result<CameraClip?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TrackingApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TrackingApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.push_up_bird.TrackingHostApi.monotonicTimeMs$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.monotonicTimeMs())
            } catch (exception: Throwable) {
              TrackingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.push_up_bird.TrackingHostApi.openAppSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openAppSettings()
              listOf(null)
            } catch (exception: Throwable) {
              TrackingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class TrackingFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TrackingFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      TrackingApiPigeonCodec()
    }
  }
  suspend fun onSample(packetArg: TrackingPacket)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.push_up_bird.TrackingFlutterApi.onSample$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(packetArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(TrackingApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onStatus(sessionArg: Long, codeArg: String, messageArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.push_up_bird.TrackingFlutterApi.onStatus$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(sessionArg, codeArg, messageArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(TrackingApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
