// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum DetectorKind { pose, face }

enum CameraAccess { granted, denied, permanentlyDenied, unavailable }

class LandmarkPacket {
  LandmarkPacket({
    required this.x,
    required this.y,
    required this.z,
    required this.confidence,
  });

  double x;

  double y;

  double z;

  double confidence;

  List<Object?> _toList() {
    return <Object?>[x, y, z, confidence];
  }

  Object encode() {
    return _toList();
  }

  static LandmarkPacket decode(Object result) {
    result as List<Object?>;
    return LandmarkPacket(
      x: result[0]! as double,
      y: result[1]! as double,
      z: result[2]! as double,
      confidence: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LandmarkPacket || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(x, other.x) &&
        _deepEquals(y, other.y) &&
        _deepEquals(z, other.z) &&
        _deepEquals(confidence, other.confidence);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LandmarkPacket(x: $x, y: $y, z: $z, confidence: $confidence)';
  }
}

class TrackingPacket {
  TrackingPacket({
    required this.session,
    required this.detector,
    required this.capturedAtMs,
    required this.sentAtMs,
    required this.inferenceMs,
    required this.imageWidth,
    required this.imageHeight,
    required this.landmarks,
    required this.smile,
    required this.detected,
    required this.sensorTimestamp,
  });

  int session;

  DetectorKind detector;

  int capturedAtMs;

  int sentAtMs;

  double inferenceMs;

  int imageWidth;

  int imageHeight;

  List<LandmarkPacket> landmarks;

  double smile;

  bool detected;

  bool sensorTimestamp;

  List<Object?> _toList() {
    return <Object?>[
      session,
      detector,
      capturedAtMs,
      sentAtMs,
      inferenceMs,
      imageWidth,
      imageHeight,
      landmarks,
      smile,
      detected,
      sensorTimestamp,
    ];
  }

  Object encode() {
    return _toList();
  }

  static TrackingPacket decode(Object result) {
    result as List<Object?>;
    return TrackingPacket(
      session: result[0]! as int,
      detector: result[1]! as DetectorKind,
      capturedAtMs: result[2]! as int,
      sentAtMs: result[3]! as int,
      inferenceMs: result[4]! as double,
      imageWidth: result[5]! as int,
      imageHeight: result[6]! as int,
      landmarks: (result[7]! as List<Object?>).cast<LandmarkPacket>(),
      smile: result[8]! as double,
      detected: result[9]! as bool,
      sensorTimestamp: result[10]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TrackingPacket || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(session, other.session) &&
        _deepEquals(detector, other.detector) &&
        _deepEquals(capturedAtMs, other.capturedAtMs) &&
        _deepEquals(sentAtMs, other.sentAtMs) &&
        _deepEquals(inferenceMs, other.inferenceMs) &&
        _deepEquals(imageWidth, other.imageWidth) &&
        _deepEquals(imageHeight, other.imageHeight) &&
        _deepEquals(landmarks, other.landmarks) &&
        _deepEquals(smile, other.smile) &&
        _deepEquals(detected, other.detected) &&
        _deepEquals(sensorTimestamp, other.sensorTimestamp);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TrackingPacket(session: $session, detector: $detector, capturedAtMs: $capturedAtMs, sentAtMs: $sentAtMs, inferenceMs: $inferenceMs, imageWidth: $imageWidth, imageHeight: $imageHeight, landmarks: $landmarks, smile: $smile, detected: $detected, sensorTimestamp: $sensorTimestamp)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is DetectorKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is CameraAccess) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is LandmarkPacket) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is TrackingPacket) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : DetectorKind.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : CameraAccess.values[value];
      case 131:
        return LandmarkPacket.decode(readValue(buffer)!);
      case 132:
        return TrackingPacket.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class TrackingHostApi {
  /// Constructor for [TrackingHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TrackingHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CameraAccess> requestCamera() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.push_up_bird.TrackingHostApi.requestCamera$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CameraAccess;
  }

  Future<void> start(
    DetectorKind detector,
    bool frontCamera,
    int session,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.push_up_bird.TrackingHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[detector, frontCamera, session],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stop() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.push_up_bird.TrackingHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<int> monotonicTimeMs() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.push_up_bird.TrackingHostApi.monotonicTimeMs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<void> openAppSettings() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.push_up_bird.TrackingHostApi.openAppSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class TrackingFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onSample(TrackingPacket packet);

  void onStatus(int session, String code, String message);

  static void setUp(
    TrackingFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.push_up_bird.TrackingFlutterApi.onSample$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final TrackingPacket arg_packet = args[0]! as TrackingPacket;
          try {
            api.onSample(arg_packet);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.push_up_bird.TrackingFlutterApi.onStatus$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_session = args[0]! as int;
          final String arg_code = args[1]! as String;
          final String arg_message = args[2]! as String;
          try {
            api.onStatus(arg_session, arg_code, arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
